In [ ]:
import numpy as np


In [ ]:
#1d array
num=np.array([2,3,5,7,11])
print(num)
print(type(num))

[ 2  3  5  7 11]
<class 'numpy.ndarray'>


In [ ]:
#2d array
num2=np.array([[2,3,5,7,11],[1,2,3,4,5],[3,4,5,6,8]])
print(num2)

[[ 2  3  5  7 11]
 [ 1  2  3  4  5]
 [ 3  4  5  6  8]]


In [ ]:
#3d array
num3=np.array([[[2,3,5,7,11],[1,2,3,4,5],[3,4,5,6,8]]])
print(num3)

[[[ 2  3  5  7 11]
  [ 1  2  3  4  5]
  [ 3  4  5  6  8]]]


In [ ]:
#array comprehension
import numpy as np
output=np.array([[x for x in range(2,21,2)],[x for x in range (1,21,2)]])
output

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [ ]:
num=np.array([2,3,5,7,11])
print(num.dtype)
print(num.shape)
print(num.size)
print(num.itemsize)

int64
(5,)
5
8


In [ ]:
# array operation
array=np.array([[1,2,3],[4,5,6]])
array
print(array>5)
print(array<=5)
print(array==5)


[[False False False]
 [False False  True]]
[[ True  True  True]
 [ True  True False]]
[[False False False]
 [False  True False]]


In [ ]:
grades=np.array([[1,2,3],[4,5,6],[5,7,8],[9,8,6]])
grades
print(grades.max())
print(grades.min())
print(grades.sum())
print(grades.mean())
print(grades.var())
print(grades.std())
print(grades.mean(axis=0))
print(grades.mean(axis=1))


9
1
64
5.333333333333333
5.722222222222222
2.3921166824012206
[4.75 5.5  5.75]


In [ ]:
num1=np.arange(1,6)
num1
num2=num1.view()
print(num2)
print(id(num1))
print(id(num2))
#deep copies
num2[1]*=5
print(num1)
print(num2)


[1 2 3 4 5]
137481430125712
137481430128784
[ 1 10  3  4  5]
[ 1 10  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:


arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
score=np.array([85,90,78,92,88])
s=score.astype(float)
print(s)
print(score.dtype)
score1=score.copy()
print(score1)
score[1]*=5
print(score)

x = np.where(score >85)

print(x)
print(score.dtype)
print(score.shape)
print(score.size)
print(score.itemsize)
print(score.max())
print(score.min())
print(score.sum())
print(score.mean())
print(score.var())
print(score.std())
print(score.mean(axis=0))
print(np.sort(score))

print()
print(score[::2])

print(score[-3:-1])

print(score[1:4])



[85. 90. 78. 92. 88.]
int64
[85 90 78 92 88]
[ 85 450  78  92  88]
(array([1, 3, 4]),)
int64
(5,)
5
8
450
78
793
158.6
21249.439999999995
145.77187657432415
158.6
[ 78  85  88  92 450]

[85 78 88]
[78 92]
[450  78  92]
